### ISSUE TITLE
Tag version released on PyPi here on GitHub as well

### ISSUE THREAD

**Issue by Oddegamra** [chantera/python-lsp-isort#2]
It appears that this repository has neither releases nor tags. On PyPi, the last released version is 0.1. I assume that this is the current HEAD commit, but is is hard to tell without additional information.

Please consider tagging the commit (e.g. with v0.1) to make it easier for distributions to refer to the commit when packaging this project.

Thank you in advance for your consideration.

**Comment by chantera** [comment]
Thank you for your suggestion.
I added a tag to the latest commit.

**Comment by Oddegamra** [comment]
Thank you!
